name: ubuntu

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        run: |
          sudo apt install -y cmake ninja-build clang clang-format lld vim
      - name: Build
        run: |
          mkdir -p build
          cd build
          rm -f CmakeCache.txt && cmake -S .. -B . --preset default -DFORMAT_SOURCES=ON -DCMAKE_INSTALL_PREFIX=local && \
          cmake --build . && ctest --output-on-failure
