name: wasi

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        run: |
          sudo apt install -y git wget tar cmake ninja-build clang-format xz-utils vim
      - name: Build
        run: |
          mkdir -p build/tools
          cd build/tools
          WASMTIME_VERSION=v13.0.0
          wget https://github.com/bytecodealliance/wasmtime/releases/download/${WASMTIME_VERSION}/wasmtime-${WASMTIME_VERSION}-x86_64-linux.tar.xz
          tar Jxf wasmtime-${WASMTIME_VERSION}-x86_64-linux.tar.xz
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/wasi-sdk-20.0-linux.tar.gz
          tar zxf wasi-sdk-20.0-linux.tar.gz
          export PATH="$(pwd)/wasmtime-${WASMTIME_VERSION}-x86_64-linux:$PATH"
          export WASISDK="$(pwd)/wasi-sdk-20.0"
          cd ..
          rm -f CmakeCache.txt && CC="${WASISDK}/bin/clang --sysroot=${WASISDK}/share/wasi-sysroot" cmake -S .. -B . --preset default -DCMAKE_C_COMPILER="" -DFORMAT_SOURCES=ON -DCMAKE_INSTALL_PREFIX=local && \
          cmake --build .
